### PR TITLE
Potential fix for issue #20

### PR DESCRIPTION
**Pull request by EvansMike**
Checks for zero length files and skips processing them.

### CODE REVIEW

**Review by mbsantiago — CHANGES_REQUESTED** [review]
Hi Mike,

Thanks for your contribution! Could you add a simple unit test to verify the issue fix? Also, consider extracting those lines into a separate function for easier testing. Appreciate your help!

Best,
Santiago

**Comment by mbsantiago** [comment]
Hey @EvansMike, it seems some other tests are now failing. I'm sorry I a bit busy at the moment, but could you please check what happened? Thanks for helping.

**Comment by EvansMike** [comment]
The extra file makes test_list_audio_files() fail at:

`assert len(audio_files) == 3`

**Comment by EvansMike** [comment]
This has become more work than I have time to spend on it.

**Pull request closed without merging**
